### ISSUE TITLE
display-line-numbers-mode is available since Emacs 26.

### ISSUE THREAD

**Issue by thapakazi** [rhoit/dot-emacs#4]
dai, instead of nlinum, there is this built in mode: **display-line-numbers-mode**

ref: 
https://www.emacswiki.org/emacs/LineNumbers#toc1
http://ergoemacs.org/emacs/emacs_line_number_mode.htmlhttp://ergoemacs.org/emacs/emacs_line_number_mode.html
https://www.reddit.com/r/emacs/comments/99e49n/displaylinenumbersmode_relative_line_numbers/

**Comment by rhoit** [comment]
I did switch to [nlinum](https://elpa.gnu.org/packages/nlinum.html) mode around *2013 Jul 31* it emacs conf was still small in [my-config](https://github.com/rhoit/my-config/commit/68054f1cc10c6d451dc4e041059d4db56b99aaff#diff-245de0c0573a1a593c59a5efdedf926bR218), before that i seem to be using *linum-mode* which is also inbuilt.

![image](https://user-images.githubusercontent.com/1684754/51785191-3b88e780-217c-11e9-9325-8aab69fd07cb.png)

*linum-mod* slowed down when viewing larger files will try *display-line-number-mode* lets see how it turns out.

**Comment by rhoit** [comment]
closing this issue, for now
